create_clock -name clk -period 5 [get_ports clk]
set_clock_transition -rise 0.001 [get_clocks clk]
set_clock_transition -fall 0.001 [get_clocks clk]
set_clock_uncertainty 0.01 [get_ports clk]
set_input_delay -max 0.01 -clock [get_clocks clk] [all_inputs]
set_output_delay -max 0.01 -clock [get_clocks clk] [all_outputs]